server:
    port: 8190

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/project_pharmacy
        username: postgres
        password: postgres
        hikari:
            idle-timeout: 10000
            connectionTimeout: 20000
            minimumIdle: 10
            maximumPoolSize: 20
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        baseline-on-migrate: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true