CREATE TABLE CATEGORY
(
    CATEGORY_ID SERIAL NOT NULL,
    NAME        VARCHAR(255) UNIQUE,
    PRIMARY KEY (CATEGORY_ID)

);

CREATE TABLE SUBCATEGORY
(
    SUBCATEGORY_ID SERIAL       NOT NULL,
    NAME           VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (SUBCATEGORY_ID)
)